# Site settings
title: _wynzlo.inspect
email: awinslow@camsys.com
description: > # this means to ignore newlines until "baseurl:"
  Ruby on Rails developer in Boston, experienced with the full stack;
  nourishing a growing passion for fantastic UX/UI and crafting innovate 
  experiences that change our world. Onward & upward.

baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://austintacious.github.io" # the base hostname & protocol for your site
twitter_username: _wynzlo
github_username:  Austintacious
sass:
  sass_dir: _sass

# Build settings
markdown: kramdown
